window.__ModuleLoader__.load({
  id: "dsh-auto-work",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    
    const ID = 'dsh-auto-work'
    const ACTIVE_ATTR = 'data-dsh-auto-work-active'
    const PANEL_EVENT = 'dsh-panel-activate'
    const PANEL_NAME = 'auto-work'
    const POLL_MS = 5000
    const TABS = ['all', 'idle', 'running', 'done', 'failed', 'archived']
    const STATUS_LABEL = { idle: '待机', running: '运行中', done: '成功', failed: '失败', archived: '已归档' }
    const labels = {
      title: '自动工作', hint: '按当前账号管理定时 Agent 工作', newJob: '新建任务', close: '返回会话', search: '搜索任务',
      empty: '还没有自动工作任务', emptyTab: '当前筛选没有任务', refresh: '刷新', all: '全部', idle: '待机', running: '运行中',
      done: '成功', failed: '失败', archived: '已归档', runs: '次执行', nextRun: '下次运行', create: '创建任务', edit: '编辑任务',
      save: '保存', cancel: '取消', titleField: '任务标题', promptField: '工作提示词', scheduleField: '执行计划（五段 cron）',
      targetField: '执行目标', commandField: '执行命令', noTarget: '未指定目标', targetSession: '会话', targetWorkspace: '工作空间', detail: '任务详情',
      history: '执行历史', noHistory: '暂无执行记录', runNow: '立即运行', pause: '暂停计划', resume: '恢复计划', remove: '删除任务',
      confirmRemove: '确认删除这个自动工作任务？', closeDetail: '关闭', loadFailed: '任务加载失败',
    }
    
    const styles = `
    [data-pane="conversation"],[class*="centerCol"]{position:relative}
    [data-dsh-auto-work-view]{position:absolute;inset:0;z-index:60;display:none;min-width:0;min-height:0;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-primary,#1f2329)}
    html[${ACTIVE_ATTR}] [data-pane="conversation"] > :not([data-dsh-auto-work-view]),html[${ACTIVE_ATTR}] [class*="centerCol"] > :not([data-dsh-auto-work-view]){display:none!important}
    html[${ACTIVE_ATTR}] [data-dsh-auto-work-view]{display:flex}
    [data-dsh-auto-work-board]{display:flex;flex:1;min-width:0;min-height:0;flex-direction:column;gap:12px;overflow:hidden;padding:14px 16px 16px;background:var(--dsw-alias-bg-base,#fff)}
    .daw-header{display:flex;align-items:center;gap:10px;min-height:32px;flex:none}.daw-title{margin:0;font-size:16px;line-height:1.2;font-weight:700}.daw-hint{color:var(--dsw-alias-label-tertiary,#8a919f);font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.daw-header-spacer{flex:1}
    .daw-search{width:210px;height:32px;padding:0 10px;border:1px solid var(--dsw-alias-border-l3,#e1e4e8);border-radius:7px;outline:none;color:inherit;background:var(--dsw-alias-bg-layer-1,#fff);font:inherit;font-size:12px}.daw-search:focus{border-color:var(--dsw-alias-brand-primary,#4b72ff)}
    .daw-btn{display:inline-flex;align-items:center;justify-content:center;gap:5px;height:32px;padding:0 12px;border:1px solid var(--dsw-alias-border-l3,#dfe3e8);border-radius:7px;color:var(--dsw-alias-label-secondary,#4d5664);background:var(--dsw-alias-bg-layer-1,#fff);font:inherit;font-size:12px;cursor:pointer}.daw-btn:hover{background:var(--dsw-alias-interactive-bg-hover,#f4f6f8)}.daw-btn-primary{border-color:var(--dsw-alias-brand-primary,#4b72ff);color:#fff;background:var(--dsw-alias-brand-primary,#4b72ff)}.daw-btn-primary:hover{background:#3e62e5}.daw-btn-danger{color:var(--dsw-alias-label-error,#d94a4a)}
    .daw-tabs{display:flex;gap:4px;min-height:0;padding:3px;border:1px solid var(--dsw-alias-border-l3,#e1e4e8);border-radius:10px;background:rgba(128,128,128,.06);overflow:auto;scrollbar-width:none;flex:none}.daw-tab{flex:1 1 auto;height:28px;padding:5px 12px;border:0;border-radius:8px;color:var(--dsw-alias-label-secondary,#596273);background:transparent;font:inherit;font-size:12px;white-space:nowrap;cursor:pointer}.daw-tab:hover{background:rgba(128,128,128,.10)}.daw-tab[data-active]{color:var(--dsw-alias-label-primary,#1f2329);background:var(--dsw-alias-bg-elevated,#fff);box-shadow:0 1px 4px rgba(0,0,0,.14);font-weight:600}.daw-count{display:inline-flex;min-width:18px;height:16px;margin-left:5px;padding:0 5px;align-items:center;justify-content:center;border-radius:999px;background:rgba(128,128,128,.14);font-size:10px}.daw-tab[data-active] .daw-count{color:#fff;background:#4b72ff}
    .daw-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:10px;align-content:start;overflow:auto;flex:1;padding:0 0 2px}.daw-card{display:flex;min-width:0;min-height:128px;flex-direction:column;gap:6px;padding:10px 12px;border:1px solid var(--dsw-alias-border-l3,#e3e6eb);border-radius:12px;text-align:left;color:inherit;background:var(--dsw-alias-bg-elevated,#fff);cursor:pointer;transition:border-color .12s ease,transform .12s ease}.daw-card:hover{border-color:var(--dsw-alias-border-l1,#8ca2ff);transform:translateY(-1px)}.daw-card[data-status=running]{border-color:#4b72ff}.daw-card-top{display:flex;align-items:center;justify-content:space-between;gap:7px;min-height:20px}.daw-status{display:inline-flex;align-items:center;gap:5px;padding:1px 8px;border:1px solid var(--dsw-alias-border-l3,#e1e4e8);border-radius:999px;color:var(--dsw-alias-label-secondary,#596273);font-size:11px}.daw-dot{width:6px;height:6px;border-radius:50%;background:currentColor}.daw-status[data-status=running]{color:#4b72ff;border-color:rgba(75,114,255,.5)}.daw-status[data-status=done]{color:#2ea66f;border-color:rgba(46,166,111,.5)}.daw-status[data-status=failed]{color:#d4574e;border-color:rgba(212,87,78,.5)}.daw-status[data-status=archived]{opacity:.72}.daw-spinner{width:12px;height:12px;margin-left:auto;border:1.5px solid #b9c5ff;border-top-color:#4b72ff;border-radius:50%;animation:daw-spin .8s linear infinite}@keyframes daw-spin{to{transform:rotate(360deg)}}.daw-card-title{display:-webkit-box;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:2;overflow-wrap:break-word;word-break:break-word;font-size:13px;font-weight:600;line-height:1.4}.daw-card-prompt{display:-webkit-box;overflow:hidden;-webkit-box-orient:vertical;-webkit-line-clamp:3;min-height:0;color:var(--dsw-alias-label-secondary,#667080);font-size:12px;line-height:1.45}.daw-card-meta{display:flex;gap:6px;margin-top:auto;flex-wrap:wrap;color:var(--dsw-alias-label-tertiary,#9098a6);font-size:11px}.daw-card-meta span{overflow:hidden;text-overflow:ellipsis}.daw-empty{grid-column:1/-1;display:flex;min-height:220px;align-items:center;justify-content:center;color:var(--dsw-alias-label-tertiary,#9098a6);font-size:13px}.daw-error{grid-column:1/-1;padding:12px 14px;border-radius:8px;color:var(--dsw-alias-label-error,#d94a4a);background:var(--dsw-alias-error-bg,#fff1f1);font-size:12px}
    .daw-entry{display:flex;align-items:center;gap:8px;width:100%;height:32px;padding:0 12px;border:0;border-radius:8px;color:var(--dsw-alias-label-secondary,#596273);background:transparent;font:inherit;font-size:13px;text-align:left;cursor:pointer;white-space:nowrap}.daw-entry:hover,.daw-entry[data-active]{color:var(--dsw-alias-label-primary,#1f2329);background:var(--dsw-specific-sidebar-nav-item-hover,#f2f4f7)}.daw-entry-icon{display:inline-flex;width:16px;height:16px;align-items:center;justify-content:center;flex:none}.daw-entry-icon svg{width:15px;height:15px}
    .daw-target-tree{height:140px;min-height:84px;max-height:420px;overflow:auto;resize:vertical;padding:4px;border:1px solid var(--dsw-alias-border-l3,#e1e4e8);border-radius:8px;font-size:12px}.daw-target-group{margin-bottom:2px}.daw-target-group-head,.daw-target-row{display:flex;align-items:center;gap:7px;width:100%;padding:5px 6px;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-primary,#1f2329);font:inherit;font-size:12px;text-align:left;cursor:pointer}.daw-target-group-head{font-weight:600;color:var(--dsw-alias-label-secondary,#596273)}.daw-target-group-head:hover,.daw-target-row:hover{background:rgba(128,128,128,.12)}.daw-target-caret{width:12px;color:var(--dsw-alias-label-tertiary,#8a919f);transition:transform .12s ease}.daw-target-caret[data-open]{transform:rotate(90deg)}.daw-target-group-name{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.daw-target-count{color:var(--dsw-alias-label-tertiary,#8a919f);font-size:11px;font-weight:400}.daw-target-body{padding-left:16px}.daw-target-row[data-selected]{background:rgba(75,114,255,.12);color:#4b72ff}.daw-target-dot{width:7px;height:7px;border:1.5px solid currentColor;border-radius:50%}
    .daw-backdrop{position:fixed;inset:0;z-index:1200;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(0,0,0,.45)}.daw-modal{display:flex;width:min(600px,100%);max-height:calc(100vh - 40px);flex-direction:column;gap:12px;overflow-y:auto;padding:18px 20px;border:1px solid var(--dsw-alias-border-l3,#e1e4e8);border-radius:14px;background:var(--dsw-alias-bg-base,#fff);box-shadow:0 18px 48px rgba(0,0,0,.28)}.daw-modal-header{display:flex;align-items:center;gap:8px}.daw-modal-title{margin:0;font-size:16px;font-weight:700}.daw-modal-close{margin-left:auto;width:28px;height:28px;border:0;border-radius:8px;color:var(--dsw-alias-label-secondary,#596273);background:transparent;font-size:18px;cursor:pointer}.daw-modal-close:hover{background:var(--dsw-alias-bg-layer-2,#f2f4f7)}.daw-modal-body{display:flex;flex-direction:column;gap:14px}.daw-field{display:flex;flex-direction:column;gap:5px}.daw-field label{color:var(--dsw-alias-label-secondary,#596273);font-size:12px}.daw-input,.daw-textarea,.daw-select{box-sizing:border-box;width:100%;padding:7px 10px;border:1px solid var(--dsw-alias-border-l3,#e1e4e8);border-radius:8px;outline:none;color:inherit;background:transparent;font:inherit;font-size:13px}.daw-input:focus,.daw-textarea:focus,.daw-select:focus{border-color:#4b72ff}.daw-textarea{min-height:120px;resize:vertical;line-height:1.5}.daw-modal-actions{display:flex;align-items:center;gap:8px;padding-top:10px;border-top:1px solid var(--dsw-alias-border-l3,#e1e4e8)}.daw-detail{display:flex;flex-direction:column;gap:12px;width:min(600px,100%)}.daw-detail-status{display:flex;align-items:center;gap:8px;font-size:14px;font-weight:620}.daw-detail-block{padding:10px;border-radius:8px;background:rgba(128,128,128,.08)}.daw-detail-block strong{display:block;margin-bottom:6px;color:var(--dsw-alias-label-tertiary,#8a919f);font-size:12px}.daw-detail-block pre{max-height:170px;overflow:auto;margin:0;white-space:pre-wrap;color:var(--dsw-alias-label-primary,#1f2329);font:inherit;font-size:12px;line-height:1.5}.daw-history{display:flex;flex-direction:column;gap:7px;margin:0;padding:0;list-style:none;color:var(--dsw-alias-label-secondary,#596273);font-size:12px}.daw-history-row{display:flex;gap:7px;align-items:flex-start;flex-wrap:wrap}.daw-history-result[data-result=succeeded]{color:#25875d}.daw-history-result[data-result=failed]{color:#c94d4d}.daw-history-result[data-result=running]{color:#4b72ff}
    @media (max-width:760px){.daw-header{padding:14px 16px;min-height:auto;flex-wrap:wrap}.daw-hint{order:3;width:100%}.daw-header-spacer{display:none}.daw-search{flex:1;min-width:120px}.daw-tabs{padding:0 16px;overflow:auto}.daw-grid{padding:16px}.daw-card{min-height:128px}}
    `
    
    function addStyles() { if (typeof document === 'undefined' || document.querySelector('style[data-dsh-auto-work-css]')) return; const style = document.createElement('style'); style.dataset.dshAutoWorkCss = ''; style.textContent = styles; document.head.append(style) }
    function el(tag, className, text) { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node }
    function button(text, className, handler) { const node = el('button', `daw-btn ${className ?? ''}`, text); node.type = 'button'; node.addEventListener('click', handler); return node }
    function formatTime(value) { if (!value) return '—'; const date = new Date(value); const delta = date.getTime() - Date.now(); if (delta > 0 && delta < 86400000) { const minutes = Math.ceil(delta / 60000); return minutes < 60 ? `+${minutes} 分钟` : `+${Math.floor(minutes / 60)} 小时` } return date.toLocaleString() }
    function targetLabel(target, targets = { sessions: [], workspaces: [] }) { if (target?.sessionId) { const session = (targets.sessions ?? []).find(row => row.id === target.sessionId); return `${labels.targetSession} · ${session?.title ?? session?.name ?? target.sessionId}` } if (target?.workspaceId) { const workspace = (targets.workspaces ?? []).find(row => row.id === target.workspaceId); return `${labels.targetWorkspace} · ${workspace?.title ?? workspace?.name ?? target.workspaceId}` } if (target?.workdir) { const workspace = (targets.workspaces ?? []).find(row => row.path === target.workdir); return `${labels.targetWorkspace} · ${workspace?.title ?? workspace?.name ?? target.workdir}` } return labels.noTarget }
    async function request(path, options = {}) { const response = await fetch(path, { credentials: 'same-origin', ...options }); const value = await response.json().catch(() => ({})); if (!response.ok) throw new Error(value.message ?? value.error ?? `请求失败（${response.status}）`); return value }
    
    class RemoteController {
      constructor(sessions) { this.sessions = sessions; this.jobs = []; this.targets = { sessions: [], workspaces: [] }; this.open = false; this.selected = undefined; this.listeners = new Set(); this.timer = undefined; this.loading = false; this.error = '' }
      getSnapshot() { return { jobs: this.jobs, targets: this.targets, open: this.open, selected: this.selected, error: this.error } }
      subscribe(fn) { this.listeners.add(fn); return () => this.listeners.delete(fn) }
      notify() { for (const fn of [...this.listeners]) fn(this.getSnapshot()) }
      start() { void this.refresh(); this.timer = setInterval(() => void this.refresh(), POLL_MS) }
      dispose() { if (this.timer) clearInterval(this.timer); this.listeners.clear() }
      openBoard() { if (!this.open) { this.open = true; this.notify(); void this.refresh() } }
      closeBoard() { if (this.open) { this.open = false; this.selected = undefined; this.notify() } }
      toggleBoard() { this.open ? this.closeBoard() : this.openBoard() }
      select(id) { if (this.jobs.some(job => job.id === id)) { this.selected = id; this.notify() } }
      closeDetail() { this.selected = undefined; this.notify() }
      async refresh() { if (this.loading) return; this.loading = true; try { const [jobs, targets] = await Promise.all([request('/api/dsh-auto-work/jobs'), request('/api/dsh-auto-work/targets')]); this.jobs = jobs.jobs ?? []; this.targets = targets ?? this.targets; this.error = '' } catch (error) { this.error = error.message ?? labels.loadFailed } finally { this.loading = false; this.notify() } }
      async create(value) { await request('/api/dsh-auto-work/jobs', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(value) }); await this.refresh() }
      async update(id, value) { await request(`/api/dsh-auto-work/jobs?id=${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(value) }); await this.refresh() }
      async remove(id) { await request(`/api/dsh-auto-work/jobs?id=${encodeURIComponent(id)}`, { method: 'DELETE' }); this.closeDetail(); await this.refresh() }
      async run(id) { await request(`/api/dsh-auto-work/jobs/run?id=${encodeURIComponent(id)}`, { method: 'POST' }); await this.refresh() }
      async toggle(id, enabled) { await this.update(id, { enabled }) }
      openSession(id) { this.closeBoard(); const open = () => { try { this.sessions?.open?.(id) } catch {} }; try { const refresh = this.sessions?.refresh; if (refresh) Promise.resolve(refresh()).then(open, open); else open() } catch { open() } }
    }
    
    function createModal(title) { const backdrop = el('div', 'daw-backdrop'); backdrop.addEventListener('click', event => { if (event.target === backdrop) backdrop.remove() }); const modal = el('div', 'daw-modal'); const header = el('header', 'daw-modal-header'); header.append(el('h2', 'daw-modal-title', title)); const close = el('button', 'daw-modal-close', '×'); close.type = 'button'; close.setAttribute('aria-label', labels.closeDetail); close.addEventListener('click', () => backdrop.remove()); header.append(close); modal.append(header); const body = el('div', 'daw-modal-body'); modal.append(body); backdrop.append(modal); return { backdrop, modal, body } }
    
    function showForm(controller, job) {
      const modal = createModal(job ? labels.edit : labels.create); const form = document.createElement('form'); const fields = {}
      const field = (label, type, value, extra = {}) => { const wrap = el('div', 'daw-field'); wrap.append(el('label', null, label)); const input = type === 'textarea' ? el('textarea', 'daw-textarea') : el(type === 'select' ? 'select' : 'input', type === 'select' ? 'daw-select' : 'daw-input'); if (type !== 'select') input.value = value ?? ''; Object.assign(input, extra); wrap.append(input); form.append(wrap); return input }
      fields.title = field(labels.titleField, 'input', job?.title, { required: true }); fields.prompt = field(labels.promptField, 'textarea', job?.prompt, { required: true }); fields.cron = field(labels.scheduleField, 'input', job?.schedule?.cron, { required: true, placeholder: '例如：0 9 * * *' })
      const targetWrap = el('div', 'daw-field'); targetWrap.append(el('label', null, labels.targetField)); const tree = el('div', 'daw-target-tree'); const targetValue = document.createElement('input'); targetValue.type = 'hidden'; targetValue.value = JSON.stringify(job?.target ?? {}); fields.target = targetValue
      const targets = controller.getSnapshot().targets; const workspaces = (targets.workspaces ?? []).map(row => ({ id: row.id, name: `${labels.targetWorkspace} · ${row.title ?? row.name ?? row.id}`, path: row.path ?? '' })); const sessions = targets.sessions ?? []; const choose = value => { const serialized = JSON.stringify(value); targetValue.value = serialized; tree.querySelectorAll('[data-selected]').forEach(node => delete node.dataset.selected); for (const node of tree.querySelectorAll('[data-target]')) if (node.dataset.target === serialized) node.dataset.selected = '' }
      for (const workspace of workspaces) { const group = el('div', 'daw-target-group'); const head = el('button', 'daw-target-group-head'); head.type = 'button'; const caret = el('span', 'daw-target-caret', '▸'); head.append(caret, el('span', 'daw-target-group-name', workspace.name)); const groupSessions = workspace.id ? sessions.filter(row => row.workspaceId === workspace.id || row.workdir === workspace.id) : []; head.append(el('span', 'daw-target-count', groupSessions.length ? String(groupSessions.length) : '')); const body = el('div', 'daw-target-body'); body.hidden = workspace.id !== ''; head.addEventListener('click', () => { body.hidden = !body.hidden; if (body.hidden) delete caret.dataset.open; else caret.dataset.open = '' }); group.append(head); const newRow = el('button', 'daw-target-row'); newRow.type = 'button'; newRow.dataset.target = JSON.stringify(workspace.id ? { workspaceId: workspace.id } : {}); newRow.append(el('span', 'daw-target-dot'), el('span', null, workspace.id ? '新增会话' : labels.noTarget)); newRow.addEventListener('click', () => choose(workspace.id ? { workspaceId: workspace.id } : {})); body.append(newRow); for (const session of groupSessions) { const row = el('button', 'daw-target-row'); row.type = 'button'; row.dataset.target = JSON.stringify({ sessionId: session.id }); row.append(el('span', 'daw-target-dot'), el('span', null, session.title ?? session.id)); row.addEventListener('click', () => choose({ sessionId: session.id })); body.append(row) } group.append(body); tree.append(group) }
      choose(JSON.parse(targetValue.value || '{}')); targetWrap.append(tree, targetValue); form.append(targetWrap)
      const actions = el('div', 'daw-modal-actions'); actions.append(button(labels.cancel, '', () => modal.backdrop.remove())); const save = button(job ? labels.save : labels.create, 'daw-btn-primary', async () => { if (!fields.title.value.trim() || !fields.prompt.value.trim() || !fields.cron.value.trim()) { window.alert('请填写标题、提示词和执行计划'); return } save.disabled = true; try { const value = { title: fields.title.value, prompt: fields.prompt.value, target: JSON.parse(fields.target.value), cron: fields.cron.value.trim() }; if (job) await controller.update(job.id, value); else await controller.create(value); modal.backdrop.remove() } catch (error) { save.disabled = false; window.alert(error.message) } }); actions.append(save); form.append(actions); modal.body.append(form); document.body.append(modal.backdrop); fields.title.focus()
    }
    
    function showDetail(controller, job) {
      const targets = controller.getSnapshot().targets
      const modal = createModal(labels.detail); const body = modal.body; const status = el('div', 'daw-detail-status'); status.append(el('span', 'daw-dot'), el('span', null, STATUS_LABEL[job.status] ?? job.status)); body.append(status)
      const block = (title, value, pre = false) => { const wrap = el('div', 'daw-detail-block'); wrap.append(el('strong', null, title)); wrap.append(pre ? el('pre', null, value) : el('div', null, value)); body.append(wrap) }; block(labels.titleField, job.title); block(labels.targetField, targetLabel(job.target, targets)); block(job.kind === 'command' ? labels.commandField : labels.promptField, job.kind === 'command' ? `${job.command ?? ''} ${job.args ?? ''}`.trim() : job.prompt, true)
      const history = el('div', 'daw-detail-block'); history.append(el('strong', null, labels.history)); const list = el('ul', 'daw-history'); const executions = job.executions ?? []; if (!executions.length) list.append(el('li', null, labels.noHistory)); for (const run of [...executions].reverse()) { const row = el('li', 'daw-history-row'); const result = run.result === 'succeeded' ? labels.done : run.result === 'failed' ? labels.failed : labels.running; const state = el('span', 'daw-history-result', result); state.dataset.result = run.result ?? 'running'; row.append(state, el('span', null, `${formatTime(run.startedAt)}${run.endedAt ? ` · ${formatTime(run.endedAt)}` : ''}`)); if (Number.isInteger(run.exitCode)) row.append(el('span', null, `退出码 ${run.exitCode}`)); if (run.error) row.append(el('span', null, run.error)); if (run.output) { const output = el('details'); const summary = el('summary', null, '执行输出'); output.append(summary, el('pre', null, run.output)); row.append(output) } list.append(row) } history.append(list); body.append(history)
      const actions = el('div', 'daw-modal-actions'); actions.append(button(labels.closeDetail, '', () => modal.backdrop.remove()), button(labels.edit, '', () => { modal.backdrop.remove(); showForm(controller, job) }), button(labels.runNow, 'daw-btn-primary', async () => { await controller.run(job.id); modal.backdrop.remove() }), button(job.schedule?.enabled ? labels.pause : labels.resume, '', async () => { await controller.toggle(job.id, !job.schedule?.enabled); modal.backdrop.remove() }), button(labels.remove, 'daw-btn-danger', async () => { if (window.confirm(labels.confirmRemove)) { await controller.remove(job.id); modal.backdrop.remove() } })); modal.modal.append(actions); document.body.append(modal.backdrop)
    }
    
    function renderBoard(container, controller, snapshot) {
      const activeTab = container._activeTab ?? 'all'; const query = container._query ?? ''; container.replaceChildren(); const board = el('div'); board.dataset.dshAutoWorkBoard = ''
      const header = el('header', 'daw-header'); header.append(el('h1', 'daw-title', labels.title), el('span', 'daw-hint', labels.hint), el('span', 'daw-header-spacer')); const search = el('input', 'daw-search'); search.type = 'search'; search.placeholder = labels.search; search.setAttribute('aria-label', labels.search); search.value = query; search.addEventListener('input', () => { container._query = search.value; renderBoard(container, controller, controller.getSnapshot()) }); header.append(search, button(labels.newJob, 'daw-btn-primary', () => showForm(controller)), button('↻', '', () => void controller.refresh()), button('←', '', () => controller.closeBoard())); board.append(header)
      const tabs = el('nav', 'daw-tabs'); const counts = Object.fromEntries(TABS.map(key => [key, key === 'all' ? snapshot.jobs.length : snapshot.jobs.filter(job => job.status === key).length])); for (const tab of TABS) { const b = el('button', 'daw-tab'); b.type = 'button'; if (activeTab === tab) b.dataset.active = ''; b.textContent = `${labels[tab]} `; b.append(el('span', 'daw-count', String(counts[tab]))); b.addEventListener('click', () => { container._activeTab = tab; renderBoard(container, controller, controller.getSnapshot()) }); tabs.append(b) } board.append(tabs)
      const grid = el('main', 'daw-grid'); if (snapshot.error) grid.append(el('div', 'daw-error', snapshot.error)); const visible = snapshot.jobs.filter(job => (activeTab === 'all' || job.status === activeTab) && (!query || `${job.title} ${job.prompt} ${job.command ?? ''} ${job.args ?? ''}`.toLowerCase().includes(query.trim().toLowerCase()))); if (!visible.length) grid.append(el('div', 'daw-empty', snapshot.jobs.length ? labels.emptyTab : labels.empty)); for (const job of visible) { const card = el('button', 'daw-card'); card.type = 'button'; card.dataset.status = job.status; const top = el('span', 'daw-card-top'); const status = el('span', 'daw-status'); status.dataset.status = job.status; status.append(el('span', 'daw-dot'), el('span', null, STATUS_LABEL[job.status] ?? job.status)); top.append(status); if (job.status === 'running') top.append(el('span', 'daw-spinner')); card.append(top, el('span', 'daw-card-title', job.title), el('span', 'daw-card-prompt', job.kind === 'command' ? `${job.command ?? ''} ${job.args ?? ''}`.trim() : job.prompt)); const meta = el('span', 'daw-card-meta'); if (job.schedule?.enabled) meta.append(el('span', null, `${labels.nextRun} ${formatTime(job.schedule.nextRunAt)}`)); meta.append(el('span', null, targetLabel(job.target, snapshot.targets)), el('span', null, `${job.executions?.length ?? 0} ${labels.runs}`)); card.append(meta); card.addEventListener('click', () => { controller.select(job.id); showDetail(controller, job) }); grid.append(card) } board.append(grid); container.append(board)
    }
    
    function conversationColumn() { return document.querySelector('[data-pane="conversation"], [class*="centerCol"], [class*="conversation"]:not([class*="sidebar"])') }
    function sidebarRoot() { const column = document.querySelector('[data-pane="sidebar"], [class*="sidebarCol"]'); return column?.querySelector('[class*="logoRow"]')?.parentElement ?? column?.firstElementChild }
    function installEntry(controller) { let entry; let root; const place = () => { root = root?.isConnected ? root : sidebarRoot(); if (!root) return; const anchor = root.querySelector('button[class*="newSession"]') ?? [...root.children].find(child => child.tagName === 'BUTTON'); if (!anchor) return; if (!entry) { entry = el('button', 'daw-entry'); entry.type = 'button'; entry.innerHTML = '<span class="daw-entry-icon"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round"><circle cx="8" cy="8" r="5.5"/><path d="M8 4.8v3.5l2.2 1.5M5.5 1.5h5"/></svg></span><span>自动工作</span>'; entry.addEventListener('click', () => controller.toggleBoard()) } if (!root.contains(entry)) root.insertBefore(entry, anchor.nextElementSibling) }; const observer = new MutationObserver(place); observer.observe(document.body, { childList: true, subtree: true }); const unsub = controller.subscribe(snapshot => { if (entry) { if (snapshot.open) entry.dataset.active = ''; else delete entry.dataset.active }; place() }); place(); return () => { observer.disconnect(); unsub(); entry?.remove() } }
    function mountBoard(controller) { let view; let unsubscribe; const ensure = () => { const column = conversationColumn(); if (!column || view) return; view = el('div'); view.dataset.dshAutoWorkView = ''; column.append(view); unsubscribe = controller.subscribe(snapshot => { if (snapshot.open) { document.documentElement.setAttribute(ACTIVE_ATTR, ''); document.dispatchEvent(new CustomEvent(PANEL_EVENT, { detail: PANEL_NAME })) } else document.documentElement.removeAttribute(ACTIVE_ATTR); renderBoard(view, controller, snapshot) }); renderBoard(view, controller, controller.getSnapshot()) }; const observer = new MutationObserver(ensure); observer.observe(document.body, { childList: true, subtree: true }); const onActivate = event => { if (event.detail !== PANEL_NAME && controller.getSnapshot().open) controller.closeBoard() }; document.addEventListener(PANEL_EVENT, onActivate); const onSidebarClick = event => { if (!controller.getSnapshot().open) return; if (event.target.closest?.('[class*="sessionRow"], [class*="projectRow"], [class*="newSession"]')) controller.closeBoard() }; document.addEventListener('click', onSidebarClick, true); ensure(); return () => { observer.disconnect(); unsubscribe?.(); document.removeEventListener(PANEL_EVENT, onActivate); document.removeEventListener('click', onSidebarClick, true); view?.remove(); document.documentElement.removeAttribute(ACTIVE_ATTR) } }
    
    function apply(ctx) { if (typeof document === 'undefined') return; ctx.effect(() => { addStyles(); const controller = new RemoteController(ctx.sessions); controller.start(); const disposeBoard = mountBoard(controller); const disposeEntry = installEntry(controller); return () => { disposeEntry(); disposeBoard(); controller.dispose() } }, `${ID}: client`) }
    
    exports.apply = apply;
    exports.inject = ["slots", "sessions"];
    return module.exports;
  }
});
